services:
  - type: web
    name: astrowind
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /_astro/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
